export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const UPDATE_EMAIL = "UPDATE_EMAIL";

export const DELETE_INVITATION = "DELETE_INVITATION";
export const ADD_INVITATION = "ADD_INVITATION";

export const ADD_GUEST = "ADD_GUEST";

export const ADD_COLUMN = "ADD_COLUMN";
export const UPDATE_COLUMN = "UPDATE_COLUMN";

export const UPDATE_TASK = "UPDATE_TASK";